server:
    port: 8081

spring:
    application:
        name: spring-boot-app
    datasource:
        url: jdbc:mysql://localhost:3306/springboot?createDatabaseIfNotExist=true
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                #format_sql: true
        show-sql: true
logging:
    level:
        io.github.chavesrodolfo: DEBUG
        org.hibernate.SQL: DEBUG
jwt:
    secretkey: your_strong_secret_key

info:
    app: Spring Boot API
    github: https://github.com/chavesrodolfo/spring-boot-api
    description: This API is an example using spring boot

management:
    endpoints:
        web:
            exposure:
                include: info, health, metrics, loggers, env, caches, prometheus
    endpoint:
        health:
            show-details: when_authorized

    