server:
    port: 8081

spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:mysql://localhost:3306/springbootprod
        username: root
        password: root
        initialization-mode: never
    banner:
        location: classpath:/banner-production.txt        

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false

logging:
    level:
        io.github.chavesrodolfo: INFO
        org.hibernate.SQL: ERROR

jwt:
    secretkey: your_strong_secret_key

management:
    endpoints:
        web:
            exposure:
                include: info, health, metrics, loggers, env, caches, prometheus
    endpoint:
        health:
            show-details: WHEN_AUTHORIZED